/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffa8a3",
        "surface-variant": "#22262b",
        "secondary": "#929bfa",
        "secondary-dim": "#8d96f4",
        "outline": "#73757a",
        "surface-container-low": "#111417",
        "on-tertiary-fixed-variant": "#4700a7",
        "on-surface": "#f8f9fe",
        "primary-dim": "#00e5ee",
        "error": "#ff716c",
        "on-primary-container": "#00575b",
        "error-container": "#9f0519",
        "surface-container": "#171a1e",
        "on-error": "#490006",
        "on-background": "#f8f9fe",
        "on-secondary-container": "#c9cdff",
        "on-primary-fixed-variant": "#006266",
        "error-dim": "#d7383b",
        "on-secondary-fixed": "#1f2882",
        "tertiary-fixed": "#bda1ff",
        "primary": "#a1faff",
        "surface-dim": "#0c0e12",
        "on-secondary-fixed-variant": "#3e47a0",
        "surface-tint": "#a1faff",
        "tertiary-container": "#7000ff",
        "inverse-on-surface": "#535559",
        "on-tertiary-container": "#f8f1ff",
        "secondary-fixed": "#cbceff",
        "surface-container-high": "#1c2025",
        "surface-container-highest": "#22262b",
        "on-primary-fixed": "#004346",
        "on-tertiary-fixed": "#1f0052",
        "secondary-container": "#343d96",
        "tertiary-fixed-dim": "#b190ff",
        "background": "#0c0e12",
        "on-secondary": "#0b1574",
        "secondary-fixed-dim": "#babfff",
        "surface-container-lowest": "#000000",
        "tertiary": "#ac89ff",
        "inverse-surface": "#f8f9fe",
        "inverse-primary": "#006a6e",
        "tertiary-dim": "#874cff",
        "on-surface-variant": "#a9abb0",
        "primary-fixed-dim": "#00e5ee",
        "surface-bright": "#282c32",
        "on-primary": "#006165",
        "outline-variant": "#46484c",
        "surface": "#0c0e12",
        "primary-fixed": "#00f4fe",
        "on-tertiary": "#290067",
        "primary-container": "#00f4fe"
      },
      fontFamily: {
        "headline": ["Inter"],
        "display": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"],
        "mono": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}
