FROM lana:v6

# Aceleração de download do HuggingFace
RUN pip install --no-cache-dir hf_transfer

# Configuração de Ambiente para Aceleração
ENV HF_HUB_ENABLE_HF_TRANSFER=1

# Tornando o Entrypoint mais flexível para o orquestrador
ENTRYPOINT ["python3"]
CMD ["scripts/inference.py"]
