FROM nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04

# Configurações para não travar em interações do apt
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Sao_Paulo

# Instalação das bibliotecas nativas de video (FFMPEG), SO e Python 3.10
RUN apt-get update && apt-get install -y \
    software-properties-common \
    python3.10 \
    python3-pip \
    python3.10-dev \
    git \
    wget \
    ffmpeg \
    libsndfile1 \
    libavcodec-dev \
    libsm6 \
    libxext6 \
    libgl2ps-dev \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Definindo o Python padrão
RUN ln -s /usr/bin/python3.10 /usr/bin/python

# Copiar definições fixas de bibliotecas (Usa o requirements.txt da raiz para garantir consistência)
COPY requirements.txt .

# Instalação das bibliotecas industriais
# Já inclui FastAPI, Uvicorn, GCS, Omegaconf, etc.
RUN pip3 install --no-cache-dir --upgrade pip && \
    pip3 install --no-cache-dir -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cu121

# Configurações Globais de Performance e Despejo de Erros
ENV PYTHONUNBUFFERED=1

# O diretório de trabalho aponta para o HD externo de "Memória",
# que será montado em /workspace com `docker run -v`
WORKDIR /workspace

LABEL project="Lana"
LABEL tier="Industrial-V19"
LABEL version="2.9"
